### ISSUE TITLE
add a link to join the #civic-hacking slack channel

### ISSUE THREAD

**Issue by mrcnc** [codefornola/codefornola.github.io#1]
Somewhere on the landing page of the website we should add a way join the #civic-hacking slack channel.

The self invite link is https://nola-slackin.herokuapp.com/

The site is powered by [slackin](https://github.com/rauchg/slackin) and you can checkout their [README](https://github.com/rauchg/slackin/blob/master/README.md#realtime-badge) for different ways of embedding it on our site.

**Comment by nihonjinrxs** [comment]
Link was added in #5
